### PR TITLE
Fixing the jobrunner

### LINKED ISSUE #10: `jobRunner.Run` isn't waiting properly for the end of the Job it creates
`jobRunner.Run` is supposed to create a given `batchv1.Job` and wait until it finishes with some outcome, and after successful run deletes the job. The current implementations is buggy and doesn't wait properly.

https://github.com/knative-sandbox/kn-plugin-event/blob/dd15346ae76b9e0c7168d2166ce45c491526a7c4/internal/k8s/jobrunner.go#L43-L52

Proper implementations should support the retries that `batchv1.Job` can specify, and return error only if those retries exceeds limits.

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Fix the `batchv1.Job` runner to properly wait for completion of remote job that is sending the event.

/kind bug

Fixes #10 

**Release Note**

```release-note
The "In Cluster Sender" has been fixed to properly shows a state of sended event. In case of sending event to clster local resources, sended waits until message is delivered on target.
```

### CODE REVIEW

File: pkg/k8s/jobrunner.go [hunk 1]
```diff
@@ -27,50 +25,71 @@ type jobRunner struct {
...
-			time.Sleep(time.Second)
+func (j *jobRunner) watchJob(meta metav1.Object, changeFn func(job *batchv1.Job) (bool, error)) error {
+	ctx := j.kube.Context()
+	jobs := j.kube.Typed().BatchV1().Jobs(meta.GetNamespace())
+	watcher, err := jobs.Watch(ctx, metav1.ListOptions{
+		FieldSelector: fmt.Sprintf("metadata.name=%s", meta.GetName()),
+	})
+	if err != nil {
+		return fmt.Errorf("%w: %v", ErrICSenderJobFailed, err)
+	}
```
Comment (dsimansk) [inline pkg/k8s/jobrunner.go:76]: Would be `defer watcher.Stop()` helpful around here to clean up resources?

Comment (dsimansk) [reply pkg/k8s/jobrunner.go:76]: And if check `RetryWatcher` from `client-go` tools. In that case it's trying to restart on closed `ResultChan` channel. That's more likely a rare case but we've seen such reports in client's issue that `ResultChan` is closed unexpectedly, but with recoverable error.

Finally I wonder if you couldn't reuse something like existing RetryWatcher code directly here.

https://github.com/kubernetes/client-go/blob/master/tools/watch/retrywatcher.go#L242-L275

Comment (cardil) [reply pkg/k8s/jobrunner.go:76]: I'm thinking that maybe that's not be possible in this exact case because of:

https://github.com/kubernetes/client-go/blob/ac207faedfb64acd5b99a2fb309b7044918b4dda/tools/watch/retrywatcher.go#L68-L71

WDYT?

Comment (dsimansk) [reply pkg/k8s/jobrunner.go:76]: Ahh, I recall that part now. Sure let's keep your watching implementation.

Do you think it's worth to address at least a bit of retry logic when `ResultChan` is closed? Of course it can done as a future enhancement/hardening.

Comment (cardil) [reply pkg/k8s/jobrunner.go:76]: I think it's good idea for an enhancement in future PR. Would you mind opening an issue?

**Comment by dsimansk** [comment]
/lgtm

@cardil feel free to unhold.
/hold

**Comment by cardil** [comment]
@dsimansk Thanks for review. 

I had to rebase. Please add LGTM flag again.

File: pkg/k8s/jobrunner.go (hunk 1 above)
Comment (dsimansk) [reply pkg/k8s/jobrunner.go:76]: Yep, I'll do first thing tomorrow.

**Review by dsimansk — APPROVED** [review]
